
get http://localhost:8080/api/items
###
get http://localhost:8080/api/admins
###
get http://localhost:8080/api/foundItems
###

post http://localhost:8080/api/admins/signin
Content-Type: application/json

{
    "username":"jPork236",
    "password":"1893"
}
###
post http://localhost:8080/api/items
Content-Type: application/json

{
    "adminId":"69bf13b9e2e3d4540d1813ce",
    "itemType":"Clothing",
    "desc":"Red Letterman Jacket",
    "loc":"AnneBelk"
}
###
post http://localhost:8080/api/foundItems
Content-Type: application/json

{
    "itemId":"69bf3d5a0bb523bbeaaf053b",
    "firstName":"App",
    "lastName":"Student",
    "isAppUser":true,
    "appId":"09382048"
}
###
post http://localhost:8080/api/foundItems
Content-Type: application/json

{
    "itemId":"69bf1499e2e3d4540d1813cf",
    "firstName":"NotApp",
    "lastName":"Individual",
    "isAppUser":false,
    "email":"bigmoves@gmail.com"
}
###
delete http://localhost:8080/api/admins/
